publishDir = "docs"
baseURL = "https://jeromie.github.io/demosite/"
languageCode = "en-us"
title = "My Test Site"
theme = "hugo-material-docs"
[[menu.main]]
  name   = "Material"
  url    = "/"
  weight = 0
  pre    = ""